# Generated by Django 2.1 on 2018-08-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='event',
			fields=[
				('event_id', models.CharField(
                    max_length=15, primary_key=True, serialize=False)),
				('event_name', models.CharField(default='', max_length=100)),
				('venue_id', models.CharField(max_length=20)),
				('em', models.CharField(max_length=1000)),
				('em_num', models.CharField(max_length=1000)),
				('day', models.DateField()),
				('time', models.TimeField()),
				('endtime', models.TimeField()),
				('status', models.IntegerField(default=0)),
				('paid', models.BooleanField(default=False)),
				('short_list', models.CharField(blank=True, default='nil', max_length=200, null=True)),
				('winner1', models.CharField(blank=True, default='nil', max_length=60)),
				('winner2', models.CharField(blank=True, default='nil', max_length=60)),
				('winner3', models.CharField(blank=True, default='nil', max_length=60)),
				('participants', models.CharField(blank=True, default='nil', max_length=10000)),
			],
			options={
				'verbose_name': 'event',
				'verbose_name_plural': 'events',
			},
		),
		migrations.CreateModel(
			name='venue',
			fields=[
				('venue_id', models.CharField(
                    max_length=20, primary_key=True, serialize=False)),
				('occupied', models.BooleanField(default=False)),
				('vm_1', models.CharField(max_length=1000)),
				('vm_2', models.CharField(default='nil', max_length=1000)),
				('vm_num_1', models.CharField(max_length=10, null=True)),
				('vm_num_2', models.CharField(default='nil', max_length=10)),
				('power', models.CharField(max_length=1000)),
				('power_num', models.CharField(max_length=10)),
				('current_event', models.CharField(default='nil', max_length=15)),
				('next_event', models.CharField(default='nil', max_length=15)),
			],
			options={
				'verbose_name': 'venue',
				'verbose_name_plural': 'venues',
			},
		),
	]
