# Generated by Django 2.1 on 2018-10-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='em',
        ),
        migrations.RemoveField(
            model_name='event',
            name='em_num',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_id',
        ),
    ]
