# Generated by Django 2.1 on 2018-10-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlroom', '0002_auto_20181025_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='venue',
        ),
    ]
