# Generated by Django 2.1 on 2018-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('excelid', models.CharField(default='excel', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('present', models.BooleanField(default=False)),
                ('stay', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('participated_events', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'userinfo',
                'verbose_name_plural': 'userinfos',
            },
        ),
    ]
