# Generated by Django 2.1 on 2018-11-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_paid_userinfo_paid_winners_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_userinfo',
            name='referralCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paid_userinfo',
            name='referralName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
