# Generated by Django 2.1 on 2018-11-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20181101_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_userinfo',
            name='referralCode',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='paid_userinfo',
            name='referralName',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
